### ISSUE TITLE
connpass API の障害時に 502 エラーになる

### ISSUE THREAD

**Issue by kt3k** [deno-ja/deno-ja#5]
イベント情報の取得に使っている connpass の API エンドポイント ( https://connpass.com/api/v1/event/?series_id=7931 ) が HTML を返す事があるらしく、その際にレンダリングが失敗して 502 レスポンスになるようです

<img width="999" alt="スクリーンショット 2022-08-16 15 54 31" src="https://user-images.githubusercontent.com/613956/184819961-1486379f-ebbd-4916-9104-455cc71fd0d8.png">

**Comment by syumai** [comment]
#6 で対応しました！
